server:
  port: 9900
spring:
  application:
    name: kafka-mongo
  data:
    mongodb:
      database: job-service
      uri: mongodb://localhost:27017
  kafka:
    producer:
      bootstrap-servers: localhost:9092