server:
  port: 9001

spring:
  application:
    name: session-service
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/session-service?createDatabaseIfNotExist=true
    username: root
    password: password
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: session-service
